Update VideoChip.md
NexTre-dev/retro-gadgets-docs pull request #42
Opened 2022-12-22 19:58 UTC by DotEXEGaming

Adding the new methods RasterCustomSprite and DrawCustomSprite introduced by RG 0.1.3.

2022-12-22 22:42 UTC, kurmachu requested changes

2022-12-22 22:42 UTC, kurmachu commented on en/docs/modules/misc/VideoChip.md
> +### DrawCustomSprite(position `vec2`, spriteSheet `SpriteSheet`, spriteOffset `vec2`, spriteSize `vec2`, tintColor `color`, backgroundColor `color`)
These lines should be rearranged to follow the Method Name -> Method Details convention.
```suggestion
### DrawCustomSprite(position `vec2`, spriteSheet `SpriteSheet`, spriteOffset `vec2`, spriteSize `vec2`, tintColor `color`, backgroundColor `color`)
⚠️ **This feature is new, as of Retro Gadgets 0.1.3, and not fully tested yet**
```

2022-12-22 22:42 UTC, kurmachu commented on en/docs/modules/misc/VideoChip.md
> +### RasterCustomSprite(position1 `vec2`, position2 `vec2`, position3 `vec2`, position4 `vec2`, spriteSheet `SpriteSheet`, spriteOffset `vec2`, spriteSize `vec2`, tintColor `color`, backgroundColor `c
These lines should be rearranged to follow the Method Name -> Method Details convention.
```suggestion
### RasterCustomSprite(position1 `vec2`, position2 `vec2`, position3 `vec2`, position4 `vec2`, spriteSheet `SpriteSheet`, spriteOffset `vec2`, spriteSize `vec2`, tintColor `color`, backgroundColor `color`)
⚠️ **This feature is new, as of Retro Gadgets 0.1.3, and not fully tested yet**
```

2022-12-22 22:54 UTC, DotEXEGaming commented
Commited both change requests.

2022-12-23 04:10 UTC, kurmachu requested changes
Image for draw text is misplaced.
![image](https://user-images.githubusercontent.com/31492625/209269201-d0612ba5-1c90-4a3d-bbda-3dc1f0218d72.png)

2022-12-23 12:01 UTC, DotEXEGaming commented
Fixed.

2022-12-23 12:02 UTC, DotEXEGaming commented
Fixed the weird S hanging around.

2022-12-23 19:56 UTC, kurmachu requested changes
So close! Just a tiny touch up, and you're good to go!

2022-12-23 19:56 UTC, kurmachu commented on en/docs/modules/misc/VideoChip.md
> +⚠️ **This feature is new, as of Retro Gadgets 0.1.3, and not fully tested yet**
Add a period to end sentence, and two spaces to allow newline in markdown.
```suggestion
⚠️ **This feature is new, as of Retro Gadgets 0.1.3, and not fully tested yet.**  
```

2022-12-23 19:56 UTC, kurmachu commented on en/docs/modules/misc/VideoChip.md
> +⚠️ **This feature is new, as of Retro Gadgets 0.1.3, and not fully tested yet**
(2nd) Add a period to end sentence, and two spaces to allow newline in markdown.
```suggestion
⚠️ **This feature is new, as of Retro Gadgets 0.1.3, and not fully tested yet.**  
```

2022-12-23 20:40 UTC, DotEXEGaming commented
Commited the corrections.

2022-12-23 20:54 UTC, kurmachu approved these changes

2022-12-23 20:54 UTC, merged