Add a section about the keyboard chips event
NexTre-dev/retro-gadgets-docs pull request #47
Opened 2023-01-28 19:27 UTC by Tresquel

Added information about the event and a tutorial on how to use it

2023-01-28 19:28 UTC, Tresquel commented
Also should close #37

2023-01-28 23:54 UTC, kurmachu requested changes
Here are a few comments and suggestions. You don't have to actually implement them, I'll merge when all chains are resolved.

2023-01-28 23:54 UTC, kurmachu commented on en/docs/modules/misc/KeyboardChip.md
> +### How to use
As there's the huge list of input names between these, maybe specify how to use what?
```suggestion
### How to use the event
```

2023-01-28 23:54 UTC, kurmachu commented on en/docs/modules/misc/KeyboardChip.md
> +Remember that it MUST be global! Prepending the local keyword will prevent the CPU from recognizing it. Adding this kind of function will cause the CPU to automatically run it whenever the user press
Prefer markdown over capitals for legibility and semantics; _remember to not use unpress?_
```suggestion
Remember that it **must** be global! Prepending the `local` keyword will prevent the CPU from recognizing it. Adding this kind of function will cause the CPU to automatically run it whenever the user presses or releases a key.
```

2023-01-28 23:54 UTC, kurmachu commented on en/docs/modules/misc/KeyboardChip.md
> +Then, select EventChannels and set the first channel to the keyboard chip.
Highlight `EventChannels`
```suggestion
Then, select `EventChannels` and set the first channel to the keyboard chip.
```

2023-01-29 13:50 UTC, Tresquel commented
Fixed now

2023-01-29 16:47 UTC, kurmachu approved these changes

2023-01-29 16:50 UTC, merged